Completed css-grid-classes. | Vera Yeh
VeraYeh/m1-321-code-solutions pull request #17
Opened 2021-03-20 03:07 UTC by VeraYeh

![image](https://user-images.githubusercontent.com/76827487/111857448-b9755300-88ee-11eb-8716-d628896db2a5.png)

2021-03-20 18:02 UTC, Zhiwutian requested changes
some CSS and HTML updates

2021-03-20 18:02 UTC, Zhiwutian commented on css-grid-classes/index.html
> +        <div>
Make sure to update each of the `row` direct children with their proper column classes

2021-03-20 18:02 UTC, Zhiwutian commented on css-grid-classes/styles.css
> +.column {
this is good for the `column-one-fourth` class, make sure to create classes for the rest of them.

2021-03-22 21:50 UTC, VeraYeh commented
![image](https://user-images.githubusercontent.com/76827487/112062947-e8254080-8b1d-11eb-8b6b-49b7c6a0cb37.png)

2021-03-23 17:14 UTC, Zhiwutian approved these changes
👍

2021-03-23 20:41 UTC, merged